name: Vercel Preview Deployment

on:
  push:
    branches-ignore:
      - main

jobs:
  Deploy-Preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts to Vercel
        run: |
          url="$(vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }})"
          echo "Deployment URL: $url"
          
      - name: Set Branch Specific Domain
        run: |
          branch_name=$(echo ${GITHUB_REF#refs/heads/} | tr '[:upper:]' '[:lower:]' | tr '/_' '-')
          new_domain="${branch_name}.tacotools.dev"
          if ! vercel domains add $new_domain --token=${{ secrets.VERCEL_TOKEN }} --scope=albertoboccolinis-projects; then
            echo "Domain already exists, skipping..."
          else
            echo "Domain added."
          fi
          vercel alias $url $new_domain --token=${{ secrets.VERCEL_TOKEN }} --scope=albertoboccolinis-projects
        env:
          GITHUB_REF: ${{ github.ref }}
