name: Clean Branch Subdomains on Main Push

on:
  push:
    branches:
      - main

jobs:
  Clean-Branch-Subdomains:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Fetch Alias Information and Filter Branch Aliases
        id: fetch_aliases
        run: |
          echo "::set-output name=branch_aliases::$(vercel alias ls --token=${{ secrets.VERCEL_TOKEN }} | grep 'branch-' | awk '{print $2}')"

      - name: Remove Branch Aliases
        run: |
          IFS=$'\n' read -r -a aliases <<< "${{ steps.fetch_aliases.outputs.branch_aliases }}"
          for alias in "${aliases[@]}"
          do
            if vercel alias rm "$alias" --yes --token=${{ secrets.VERCEL_TOKEN }}; then
              echo "Removed alias: $alias"
            else
              echo "Failed to remove alias: $alias"
            fi
          done
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
